# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46202cdbd8c4b750651c6adc97d20ab93b2477841ac12a7f71e19af9fb778fe86312903ec9d10ae0874eec4dc490228cd44e76d897253a68b00e4c97e4e29ff6

test:
  secret_key_base: e16b6d8ce23fe3f330d32b0f8d2c784c3d7658d289cf11ab2fb5b78c007f3767ea3853bb548010eda0495eac3822d38199bb09be341528080e5e515954bd3f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
